-- ============================================================
-- Complete setup for the `user_profiles` table
-- Run in Supabase Dashboard → SQL Editor (safe to run multiple times)
--
-- Notes:
--  * The table already exists in this project (with 1 LINE user row),
--    so CREATE TABLE IF NOT EXISTS is a no-op — existing data is kept.
--  * The ALTER statements add what's missing (password column, unique).
--  * The trigger makes updated_at update itself automatically.
-- ============================================================

-- 1) Full table definition (reference / fresh installs only)
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  "userId"      text NOT NULL,
  "displayName" text,
  "pictureUrl"  text,
  "statusMessage" text,
  status        text,
  updated_at    timestamp NOT NULL,
  role          text,
  ai_enabled    boolean DEFAULT true,
  ai_status     boolean DEFAULT true,
  password      text
);

-- 2) Add the password column (SHA-256 hash) — required for registration login
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS password text;

-- 3) Prevent duplicate userId (email) registrations.
--    DROP first because Postgres folds the name to lowercase
--    (user_profiles_userid_key) — avoids the 42P07 "already exists" error.
ALTER TABLE public.user_profiles
  DROP CONSTRAINT IF EXISTS user_profiles_userid_key;
ALTER TABLE public.user_profiles
  ADD CONSTRAINT user_profiles_userid_key UNIQUE ("userId");

-- 4) Auto-update updated_at on any change (insert or update)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_profiles_updated_at ON public.user_profiles;
CREATE TRIGGER trg_user_profiles_updated_at
  BEFORE INSERT OR UPDATE ON public.user_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 5) RLS policies — allow the app (anon role = publishable key) to insert
--    new registrations and read profiles (needed for login checks).
--    Fixes: "new row violates row-level security policy".
DROP POLICY IF EXISTS user_profiles_anon_insert ON public.user_profiles;
CREATE POLICY user_profiles_anon_insert ON public.user_profiles
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS user_profiles_anon_select ON public.user_profiles;
CREATE POLICY user_profiles_anon_select ON public.user_profiles
  FOR SELECT TO anon, authenticated
  USING (true);
